baseURL: "https://pascalmichaillat.org/hugo-website/" 
title: Yiwei Si
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
    tag: tags

menu:
    main:
         - name: Talks
           url: talks/
           weight: 1
         - name: Teaching
           url: teaching/
           weight: 2
      #  - name: Books
      #    url: books/
      #    weight: 5 
      #  - name: Papers
      #    url: papers/
      #    weight: 2
      #  - name: Courses
      #    url: courses/
      #    weight: 3
      #  - name: Data
      #    url: data/
      #    weight: 4 
      #  - name: Blog
      #    url: https://en.wikipedia.org/wiki/Moritz-Maria_von_Igelfeld_(character)
      #    weight: 6

params:
    description: "This website hosts Yiwei Si's research papers, books, course materials, data, curriculum vitae, and contact information."
    author: Yiwei Si
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["books","courses","papers","data"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Yiwei Si
          subtitle: "Hi! I’m a third-year PhD student in Linguistics at the Faculty of Linguistics, Philology and Phonetics at the University of Oxford. I’m fortunate to be supported by both the Clarendon Scholarship and the Hanseatic Scholarship. As part of the Hanseatic Scholarship, I’ll be spending a year as a visiting researcher at the Leibniz-Centre General Linguistics (ZAS) in Berlin, starting in October 2025.<br><br>
            My main research interest lies in morphology and its interfaces with phonology, syntax, and semantics. In my DPhil thesis, I explore how verbal particles in German contribute to the expression of aspect from both syntactic and semantic perspectives, using a neo-constructionist approach to word formation. I’m additionally interested in syntax, psycholinguistics and first language acquisition.<br><br>
            Before starting my PhD, I completed an MPhil in Linguistics at Oxford in 2022. I earned my Bachelor's degree in German Studies from Beijing Foreign Studies University in China.<br><br>
            Outside of linguistics, I enjoy exploring local restaurants, practicing yoga, playing tennis, and travelling."
          imageUrl: "yiweisi.jpg"
          imageWidth: 140
          imageHeight: 140
          buttons:
             - name: Talks
               url: talks/
             - name: Teaching
               url: teaching/
        #    - name: Papers
        #      url: papers/
        #    - name: Data
        #      url: data/
        #    - name: Books
        #      url: books/
        #    - name: Courses
        #      url: courses/
        #    - name: Tags
        #      url: tags/
        #    - name: Archive
        #      url: archive/
          #  - name: Blog
          #    url: https://en.wikipedia.org/wiki/Moritz-Maria_von_Igelfeld_(character)

    socialIcons:
        - name: CV
          url: cv.pdf
        - name: Email
          url: mailto:yiwei.si@ling-phil.ox.ac.uk
      #  - name: Zoom
      #    url: https://www.zoom.us/my/igelfeld
      #  - name: Location
      #    url: location/
      #  - name: Office Hours
      #    url: officehours/
      #  - name: Google Scholar
      #    url: https://scholar.google.com/citations?user=cL23w-4AAAAJ
      #  - name: GitHub
      #    url: https://github.com/pmichaillat
      #  - name: Substack
      #    url: https://pmichaillat.substack.com
      #  - name: YouTube
      #    url: https://www.youtube.com/@pmichaillat
      #  - name: Twitter
      #    url: https://x.com/pmichaillat
      #  - name: Bluesky
      #    url: https://bsky.app/profile/pmichaillat.bsky.social

    assets:
        customCSS:
          - css/custom.css
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Yiwei Si"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2